version: "1"
services:
  db:
    image: postgres:15.2
    container_name: clockshop-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: clockshop
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - clockshop-network

  clockshop:
    container_name: clockshop-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/clockshop
    networks:
      - clockshop-network

networks:
  clockshop-network:
    driver: bridge
